base_url = "https://robitzs.ch"
title = "robitzs.ch"
description = "the personal website of britton robitzsch"
default_language = "en"

compile_sass = true
build_search_index = false
generate_feed = true
ignored_content = [
    "**/_*.{png,svg}",  # unoptimized images
]

# theme is inlined
# theme = "apollo"

taxonomies = [
    { name = "tags" },
]

[markdown]
highlight_code = true
highlight_theme = "zenburn"
extra_syntaxes_and_themes = [
    "extra/syntax/"
]
render_emoji = false
external_links_target_blank = true
external_links_no_referrer = true

[extra]
favicon = "/image/favicon.svg"
stylesheets = []
fonts = [
    { path = "jetbrains-mono", name = "JetBrainsMono" }
]

menu = [
    { name = "/posts", url = "@/posts/_index.md" },
    { name = "/projects", url = "@/projects.md" },
    { name = "/about", url = "@/about.md" },
    { name = "git", url = "https://github.com/brittonr", external = true },
]

me_links = [
    { name = "github", url = "https://github.com/brittonr" },
    { name = "linkedin", url = "https://www.linkedin.com/in/brittonrobitzsch/"},
]

